# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fcc4d8bb1423b520af4a5caf1f7d04d50e952e0a17db8bebdd56ea205c8ebf6a80707c7945996788ba22b2a2f1bb8c7906271b17b1b31b9b747259adbccfc13

test:
  secret_key_base: 44576078caac83a04c14e8ae49d464dd170deaea1ba5f3baa9a6749258dbaaec43fa1d442e6e449a6dee4267f9c876ceca2b48c9a0688384a2efbf10a49f72c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
